name: Client Pull Request

on:
  pull_request:
    branches:
      - main
    paths:
      - games/*/client/**

jobs:
  changed-files:
    runs-on: ubuntu-latest
    name: Test changed-files
    outputs:
      matrix: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - uses: actions/checkout@v4
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with: 
          dir_names: true
          dir_names_max_depth: 2
          matrix: true
          files: |
            games/*/client/**

  create-matrix:
    runs-on: ubuntu-latest
    name: Create matrix
    needs: [changed-files]
    outputs:
      variants: ${{ steps.set-variants.outputs.variants }}
      directory: ${{ steps.set-variants.outputs.directory }} # This output will pass the current directory
    strategy:
      matrix: 
        directories: ${{ fromJSON(needs.changed-files.outputs.matrix) }}
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Variants
        id: set-variants
        working-directory: ${{ matrix.directories }}
        run: |
          CONFIG=$(yq e -o=json '.' variants.yaml)
          VARIANTS=$(echo $CONFIG | jq -r '.variants | @json')
          if [[ -z "$VARIANTS" || "$VARIANTS" == "null" ]]; then
            echo "::set-output name=has_variants::false"
          else
            echo "::set-output name=has_variants::true"
            echo "::set-output name=variants::$VARIANTS"
          fi
          echo "::set-output name=directory::${{ matrix.directories }}"  # Setting the directory output

  build-variants:
    runs-on: ubuntu-latest
    needs: create-matrix
    if: needs.create-matrix.outputs.has_variants == 'true'
    strategy:
      matrix:
        variant: ${{ fromJSON(needs.create-matrix.outputs.variants) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Variant
        working-directory: ${{ needs.create-matrix.outputs.directory }}
        run: |
          echo "Running build for variant: ${{ matrix.variant }} in directory: ${{ needs.create-matrix.outputs.directory }}"
          npm run build:${{ matrix.variant }}

  run-default-build:
    runs-on: ubuntu-latest
    needs: create-matrix
    if: needs.create-matrix.outputs.has_variants == 'false'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Default Build
        working-directory: ${{ needs.create-matrix.outputs.directory }}
        run: |
          echo "Running default build in directory: ${{ needs.create-matrix.outputs.directory }}"
          npm run build
