name: Client Pull Request

on:
  pull_request:
    branches:
      - main
    paths:
      - games/*/client/**

jobs:
  changed-files:
    runs-on: ubuntu-latest
    name: Get Changed Directories
    outputs:
      directories: ${{ steps.get-changed-dirs.outputs.all_changed_files }}
    steps:
      - uses: actions/checkout@v4

      - name: Get changed directories
        id: get-changed-dirs
        uses: tj-actions/changed-files@v44
        with:
          dir_names: true
          dir_names_max_depth: 2
          matrix: true
          files: |
            games/*/client/**

      - name: Load Build Configuration
        id: load-config
        run: |
          echo "::set-output name=config::$(cat games/build-config.json)"

      - name: Set up matrix
        id: set-matrix
        run: |
          echo "JSON output of changed directories:"
          echo '${{ fromJson(steps.get-changed-dirs.outputs.all_changed_files) }}'