name: Build Client

on:
  workflow_call:
    inputs:
      build-command:
        description: 'Command to build the client'
        required: true
        type: string

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Debug Build Config
        run: |
          echo "Using command: ${{ inputs.build-command }}"
