name: Client Pull Request

on:
  pull_request:
    branches:
      - main
    paths:
      - games/*/client/**

jobs:
  changed-files:
    runs-on: ubuntu-latest
    name: Get Changed Directories
    outputs:
      matrix: ${{ steps.get-changed-dirs.outputs.all_changed_files }}
    steps:
      - uses: actions/checkout@v4

      - name: Get changed directories
        id: get-changed-dirs
        uses: tj-actions/changed-files@v44
        with:
          dir_names: true
          dir_names_max_depth: 2
          matrix: true
          files: |
            games/*/client/**

  load-build-config:
    runs-on: ubuntu-latest
    needs: [changed-files]
    strategy:
      matrix:
        directories: ${{ fromJson(needs.changed-files.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4

      - name: Read and Parse YAML
        id: parse_yaml
        uses: mikefarah/yq@v4
        with:
          cmd: yq . ${{ matrix.directories }}/variants.yaml

      - name: Echo Variables
        run: echo ${{ steps.parse_yaml.outputs.result }}
