name: Client Pull Request

on:
  pull_request:
    branches:
      - main
    paths:
      - games/*/client/**

jobs:
  changed-files:
    runs-on: ubuntu-latest
    name: Test changed-files
    outputs:
      matrix: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - uses: actions/checkout@v4
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with: 
          dir_names: true
          dir_names_max_depth: 2
          matrix: true
          files: |
            games/*/client/**
  
  create-matrix:
    runs-on: ubuntu-latest
    name: Create matrix
    needs: [changed-files]
    outputs:
      variants: ${{ steps.set-variants.outputs.variants }}
    strategy:
      matrix: 
        directories: ${{ fromJSON(needs.changed-files.outputs.matrix) }}
      max-parallel: 4
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: |
          echo ${{ matrix.directories }}
      - name: Set Variants
        id: set-variants
        working-directory: ${{ matrix.directories }}
        run: |
          CONFIG=$(yq e -o=json '.' variants.yaml)
          VARIANTS=$(echo $CONFIG | jq -r '.variants')
          echo "::set-output name=variants::$VARIANTS"

  run-variants:
    runs-on: ubuntu-latest
    needs: create-matrix
    strategy:
      matrix:
        variant: ${{ fromJSON(needs.create-matrix.outputs.variants) }}
    steps:
      - name: Print Variant Type
        run: |
          echo "Running job for variant: ${{ matrix.variant }}"