name: Model Pull Request

on:
  pull_request:
    branches:
      - main
    paths:
      - games/*/model/**

jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: Test changed-files
    outputs:
      matrix: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - uses: actions/checkout@v4
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with: 
          dir_names: true
          matrix: true
          files: |
            games/*/model/**
  
  matrix-job:
    runs-on: ubuntu-latest
    name: Run Matrix Job
    needs: [changed-files]
    strategy:
      matrix: 
        directories: ${{ fromJSON(needs.changed-files.outputs.matrix) }}
      max-parallel: 4
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: |
          echo ${{ matrix.directories }}